blueprint:
  name: "⌚ Wrist Assistant – Watch Notification"
  author: "Wrist Assistant"
  description: >
    Send rich, actionable push notifications straight to your Apple Watch.


    Pick a **category** to add quick-action buttons (toggle, lock, vacuum, alarm, etc.)
    and point them at any Home Assistant entity — no YAML required.


    **Quick start:** fill in the message below, save the script, then call it
    from any automation.
  domain: script
  input:
    message:
      name: Message
      description: Notification body text.
      selector:
        text:
    title:
      name: Title
      description: Optional title displayed above the message.
      default: ""
      selector:
        text:
    category:
      name: Category
      description: Action buttons shown on the notification.
      default: ""
      selector:
        select:
          mode: dropdown
          options:
            - label: "None (info only)"
              value: ""
            - label: "Toggle Entity"
              value: "ENTITY_TOGGLE"
            - label: "Turn On Entity"
              value: "ENTITY_TURN_ON"
            - label: "Turn Off Entity"
              value: "ENTITY_TURN_OFF"
            - label: "Open (cover/valve)"
              value: "OPEN_CONTROL"
            - label: "Close (cover/valve)"
              value: "CLOSE_CONTROL"
            - label: "Lock"
              value: "LOCK_CONTROL"
            - label: "Unlock"
              value: "UNLOCK_CONTROL"
            - label: "Alarm Control"
              value: "ALARM_CONTROL"
            - label: "Vacuum Control (start, pause, return home)"
              value: "VACUUM_CONTROL"
            - label: "Confirm Action"
              value: "CONFIRM_ACTION"
            - label: "Activate Scene"
              value: "SCENE_ACTIVATE"
            - label: "Custom HA Actions"
              value: "HA_CUSTOM"
    priority:
      name: Priority
      description: >
        Interruption level. Passive delivers silently, Active is the default,
        Time Sensitive breaks through Focus/DND, Critical overrides mute.
      default: "active"
      selector:
        select:
          mode: dropdown
          options:
            - label: "Passive (silent delivery)"
              value: "passive"
            - label: "Active (default)"
              value: "active"
            - label: "Time Sensitive (breaks Focus)"
              value: "time-sensitive"
            - label: "Critical (overrides mute)"
              value: "critical"
    sound:
      name: Sound
      description: Notification sound.
      default: "default"
      selector:
        select:
          mode: dropdown
          options:
            - label: "Default sound"
              value: "default"
            - label: "Silent"
              value: ""
    target:
      name: Target Watch
      description: >
        Watch to send to. Leave empty to send to all registered watches.
      default: ""
      selector:
        device:
          filter:
            - integration: wrist_assistant
    tag:
      name: Tag
      description: >
        Collapse key. A new notification with the same tag replaces the
        previous one instead of stacking.
      default: ""
      selector:
        text:
    group:
      name: Group
      description: >
        Thread ID to group related notifications together in the watch
        notification center.
      default: ""
      selector:
        text:
    action_entity:
      name: Action Entity
      description: >
        Entity for action buttons to act on. Required for categories like
        Toggle, Turn On/Off, Open/Close, Lock/Unlock, and Scene Activate.
      default: ""
      selector:
        entity:
    action_service:
      name: Action Service
      description: >
        Service for the Confirm Action category. Domain is auto-detected
        from the Action Entity.
      default: ""
      selector:
        select:
          custom_value: true
          mode: dropdown
          options:
            - label: "None"
              value: ""
            - label: "Turn On"
              value: "turn_on"
            - label: "Turn Off"
              value: "turn_off"
            - label: "Toggle"
              value: "toggle"
            - label: "Open Cover"
              value: "open_cover"
            - label: "Close Cover"
              value: "close_cover"
            - label: "Lock"
              value: "lock"
            - label: "Unlock"
              value: "unlock"
            - label: "Arm Home"
              value: "alarm_arm_home"
            - label: "Arm Away"
              value: "alarm_arm_away"
            - label: "Disarm"
              value: "alarm_disarm"
            - label: "Start (vacuum)"
              value: "start"
            - label: "Pause (vacuum)"
              value: "pause"
            - label: "Return to Base (vacuum)"
              value: "return_to_base"

mode: parallel
max: 10

sequence:
  - variables:
      bp_message: !input message
      bp_title: !input title
      bp_category: !input category
      bp_priority: !input priority
      bp_sound: !input sound
      bp_target_device: !input target
      bp_tag: !input tag
      bp_group: !input group
      bp_action_entity: !input action_entity
      bp_action_service: !input action_service
  - service: wrist_assistant.send_notification
    data: >
      {%- set d = namespace(items=[("message", bp_message), ("priority", bp_priority)]) -%}
      {%- if bp_title %}{%- set d.items = d.items + [("title", bp_title)] -%}{%- endif -%}
      {%- if bp_category %}{%- set d.items = d.items + [("category", bp_category)] -%}{%- endif -%}
      {%- if bp_sound %}{%- set d.items = d.items + [("sound", bp_sound)] -%}{%- endif -%}
      {%- if bp_target_device -%}
        {%- set ids = device_attr(bp_target_device, 'identifiers') | list -%}
        {%- if ids %}{%- set d.items = d.items + [("target", ids[0][1] | replace('watch_', ''))] -%}{%- endif -%}
      {%- endif -%}
      {%- if bp_tag %}{%- set d.items = d.items + [("tag", bp_tag)] -%}{%- endif -%}
      {%- if bp_group %}{%- set d.items = d.items + [("group", bp_group)] -%}{%- endif -%}
      {%- set extra = namespace(items=[]) -%}
      {%- if bp_action_entity -%}
        {%- set extra.items = extra.items + [("entity_id", bp_action_entity)] -%}
        {%- set extra.items = extra.items + [("domain", bp_action_entity.split('.')[0])] -%}
      {%- endif -%}
      {%- if bp_action_service %}{%- set extra.items = extra.items + [("service", bp_action_service)] -%}{%- endif -%}
      {%- if extra.items %}{%- set d.items = d.items + [("data", dict(extra.items))] -%}{%- endif -%}
      {{ dict(d.items) }}
