blueprint:
  name: "Watch Notification"
  author: "Wrist Assistant"
  description: >
    Send actionable push notifications to your Apple Watch.


    Define up to 4 action buttons — each calls a Home Assistant service
    when tapped. Use `domain.service` format (e.g. `light.toggle`,
    `lock.lock`, `vacuum.return_to_base`).


    Leave action slots empty to skip them. A notification with no actions
    shows as info-only (title + message, no buttons).
  domain: script
  input:
    message:
      name: Message
      description: Notification body text.
      selector:
        text:
    title:
      name: Title
      description: Optional title displayed above the message.
      default: ""
      selector:
        text:
    action_1_title:
      name: Action 1 Title
      description: Button label for the first action.
      default: ""
      selector:
        text:
    action_1_service:
      name: Action 1 Service
      description: >
        Service to call (domain.service format, e.g. light.toggle).
      default: ""
      selector:
        text:
    action_1_entity:
      name: Action 1 Entity
      description: Entity to pass to the service call.
      default: ""
      selector:
        entity:
    action_2_title:
      name: Action 2 Title
      description: Button label for the second action.
      default: ""
      selector:
        text:
    action_2_service:
      name: Action 2 Service
      description: >
        Service to call (domain.service format, e.g. lock.lock).
      default: ""
      selector:
        text:
    action_2_entity:
      name: Action 2 Entity
      description: Entity to pass to the service call.
      default: ""
      selector:
        entity:
    action_3_title:
      name: Action 3 Title
      description: Button label for the third action.
      default: ""
      selector:
        text:
    action_3_service:
      name: Action 3 Service
      description: >
        Service to call (domain.service format).
      default: ""
      selector:
        text:
    action_3_entity:
      name: Action 3 Entity
      description: Entity to pass to the service call.
      default: ""
      selector:
        entity:
    action_4_title:
      name: Action 4 Title
      description: Button label for the fourth action.
      default: ""
      selector:
        text:
    action_4_service:
      name: Action 4 Service
      description: >
        Service to call (domain.service format).
      default: ""
      selector:
        text:
    action_4_entity:
      name: Action 4 Entity
      description: Entity to pass to the service call.
      default: ""
      selector:
        entity:
    priority:
      name: Priority
      description: >
        Interruption level. Passive delivers silently, Active is the default,
        Time Sensitive breaks through Focus/DND, Critical overrides mute.
      default: "active"
      selector:
        select:
          mode: dropdown
          options:
            - label: "Passive (silent delivery)"
              value: "passive"
            - label: "Active (default)"
              value: "active"
            - label: "Time Sensitive (breaks Focus)"
              value: "time-sensitive"
            - label: "Critical (overrides mute)"
              value: "critical"
    sound:
      name: Sound
      description: Notification sound.
      default: "default"
      selector:
        select:
          mode: dropdown
          options:
            - label: "Default sound"
              value: "default"
            - label: "Silent"
              value: ""
    target:
      name: Target Watch
      description: >
        Watch to send to. Leave empty to send to all registered watches.
      default: ""
      selector:
        device:
          filter:
            - integration: wrist_assistant
    tag:
      name: Tag
      description: >
        Collapse key. A new notification with the same tag replaces the
        previous one instead of stacking.
      default: ""
      selector:
        text:
    group:
      name: Group
      description: >
        Thread ID to group related notifications together in the watch
        notification center.
      default: ""
      selector:
        text:

mode: parallel
max: 10

sequence:
  - variables:
      bp_message: !input message
      bp_title: !input title
      bp_a1_title: !input action_1_title
      bp_a1_service: !input action_1_service
      bp_a1_entity: !input action_1_entity
      bp_a2_title: !input action_2_title
      bp_a2_service: !input action_2_service
      bp_a2_entity: !input action_2_entity
      bp_a3_title: !input action_3_title
      bp_a3_service: !input action_3_service
      bp_a3_entity: !input action_3_entity
      bp_a4_title: !input action_4_title
      bp_a4_service: !input action_4_service
      bp_a4_entity: !input action_4_entity
      bp_priority: !input priority
      bp_sound: !input sound
      bp_target_device: !input target
      bp_tag: !input tag
      bp_group: !input group
  - service: wrist_assistant.send_notification
    data: >
      {%- set d = namespace(items=[("message", bp_message), ("priority", bp_priority)]) -%}
      {%- if bp_title %}{%- set d.items = d.items + [("title", bp_title)] -%}{%- endif -%}
      {%- if bp_sound %}{%- set d.items = d.items + [("sound", bp_sound)] -%}{%- endif -%}
      {%- if bp_target_device -%}
        {%- set ids = device_attr(bp_target_device, 'identifiers') | list -%}
        {%- if ids %}{%- set d.items = d.items + [("target", ids[0][1] | replace('watch_', ''))] -%}{%- endif -%}
      {%- endif -%}
      {%- if bp_tag %}{%- set d.items = d.items + [("tag", bp_tag)] -%}{%- endif -%}
      {%- if bp_group %}{%- set d.items = d.items + [("group", bp_group)] -%}{%- endif -%}
      {%- set actions = namespace(list=[]) -%}
      {%- set slots = [
        (bp_a1_title, bp_a1_service, bp_a1_entity),
        (bp_a2_title, bp_a2_service, bp_a2_entity),
        (bp_a3_title, bp_a3_service, bp_a3_entity),
        (bp_a4_title, bp_a4_service, bp_a4_entity),
      ] -%}
      {%- for title, svc, entity in slots -%}
        {%- if title -%}
          {%- set a = namespace(items=[("title", title)]) -%}
          {%- if svc and '.' in svc -%}
            {%- set a.items = a.items + [("domain", svc.split('.')[0]), ("service", svc.split('.')[1])] -%}
          {%- endif -%}
          {%- if entity %}{%- set a.items = a.items + [("entity_id", entity)] -%}{%- endif -%}
          {%- set actions.list = actions.list + [dict(a.items)] -%}
        {%- endif -%}
      {%- endfor -%}
      {%- if actions.list %}{%- set d.items = d.items + [("actions", actions.list)] -%}{%- endif -%}
      {{ dict(d.items) }}
