blueprint:
  name: "Watch Notification"
  author: "Wrist Assistant"
  description: >
    Send actionable push notifications to your Apple Watch.


    Define up to 4 action buttons using Home Assistant's native service
    picker. Choose any service, target entity, and service data.


    Leave action slots empty to skip them. A notification with no actions
    shows as info-only (title + message, no buttons).
  domain: script
  input:
    message:
      name: Message
      description: Notification body text.
      selector:
        text:
    title:
      name: Title
      description: Optional title displayed above the message.
      default: ""
      selector:
        text:

    section_action_1:
      name: Action 1
      icon: mdi:gesture-tap-button
      collapsed: false
      input:
        action_1_title:
          name: Button Label
          description: >
            Text shown on the button. Leave blank to auto-generate
            from the service name (e.g. "Turn On").
          default: ""
          selector:
            text:
        action_1:
          name: Action
          description: >
            Service to call when the button is tapped. Use the picker
            to choose any service, target entity, and service data.
          default: []
          selector:
            action:

    section_action_2:
      name: Action 2
      icon: mdi:gesture-tap-button
      collapsed: true
      input:
        action_2_title:
          name: Button Label
          description: Text shown on the button.
          default: ""
          selector:
            text:
        action_2:
          name: Action
          description: Service to call when the button is tapped.
          default: []
          selector:
            action:

    section_action_3:
      name: Action 3
      icon: mdi:gesture-tap-button
      collapsed: true
      input:
        action_3_title:
          name: Button Label
          description: Text shown on the button.
          default: ""
          selector:
            text:
        action_3:
          name: Action
          description: Service to call when the button is tapped.
          default: []
          selector:
            action:

    section_action_4:
      name: Action 4
      icon: mdi:gesture-tap-button
      collapsed: true
      input:
        action_4_title:
          name: Button Label
          description: Text shown on the button.
          default: ""
          selector:
            text:
        action_4:
          name: Action
          description: Service to call when the button is tapped.
          default: []
          selector:
            action:

    section_options:
      name: Options
      icon: mdi:tune
      collapsed: true
      input:
        priority:
          name: Priority
          description: >
            Interruption level. Passive delivers silently, Active is the
            default, Time Sensitive breaks through Focus/DND, Critical
            overrides mute.
          default: "active"
          selector:
            select:
              mode: dropdown
              options:
                - label: "Passive (silent delivery)"
                  value: "passive"
                - label: "Active (default)"
                  value: "active"
                - label: "Time Sensitive (breaks Focus)"
                  value: "time-sensitive"
                - label: "Critical (overrides mute)"
                  value: "critical"
        sound:
          name: Sound
          description: >
            Notification sound. Preview sounds at
            mixkit.co/free-sound-effects/notification/ or in the iOS app
            under Settings > Notification Sounds.
          default: "default"
          selector:
            select:
              mode: dropdown
              custom_value: true
              options:
                - label: "Default sound"
                  value: "default"
                - label: "Silent"
                  value: ""
                - label: "Access Allowed"
                  value: "Access-Allowed.caf"
                - label: "Arabian Harp"
                  value: "Arabian-Harp.caf"
                - label: "ATM Keypress"
                  value: "ATM-Keypress.caf"
                - label: "Bell"
                  value: "Bell.caf"
                - label: "Bubble Pop"
                  value: "Bubble-Pop.caf"
                - label: "Clear Announce"
                  value: "Clear-Announce.caf"
                - label: "Confirmation"
                  value: "Confirmation.caf"
                - label: "Correct Answer"
                  value: "Correct-Answer.caf"
                - label: "Correct Answer Reward"
                  value: "Correct-Answer-Reward.caf"
                - label: "Digital Quick"
                  value: "Digital-Quick.caf"
                - label: "Doorbell Single"
                  value: "Doorbell-Single.caf"
                - label: "Doorbell Tone"
                  value: "Doorbell-Tone.caf"
                - label: "Dry Pop"
                  value: "Dry-Pop.caf"
                - label: "Elevator Tone"
                  value: "Elevator-Tone.caf"
                - label: "Gaming Lock"
                  value: "Gaming-Lock.caf"
                - label: "Guitar Alert"
                  value: "Guitar-Alert.caf"
                - label: "Happy Bells"
                  value: "Happy-Bells.caf"
                - label: "Interface Back"
                  value: "Interface-Back.caf"
                - label: "Interface Remove"
                  value: "Interface-Remove.caf"
                - label: "Interface Start"
                  value: "Interface-Start.caf"
                - label: "Light Button"
                  value: "Light-Button.caf"
                - label: "Long Pop"
                  value: "Long-Pop.caf"
                - label: "Magic Marimba"
                  value: "Magic-Marimba.caf"
                - label: "Magic Ring"
                  value: "Magic-Ring.caf"
                - label: "Option Select"
                  value: "Option-Select.caf"
                - label: "Positive"
                  value: "Positive.caf"
                - label: "Sci-Fi Click"
                  value: "Sci-Fi-Click.caf"
                - label: "Tile Reveal"
                  value: "Tile-Reveal.caf"
                - label: "Wrong Answer"
                  value: "Wrong-Answer.caf"
        target:
          name: Target Watch
          description: >
            Watch to send to. Leave empty to send to all registered watches.
          default: ""
          selector:
            device:
              filter:
                - integration: wrist_assistant
                  model: Apple Watch
        tag:
          name: Tag
          description: >
            Collapse key — a new notification with the same tag replaces the
            previous one instead of stacking. For example, set tag to
            "front_door" on a door-open alert so repeated opens show only
            the latest notification rather than piling up.
          default: ""
          selector:
            text:
        group:
          name: Group
          description: >
            Groups related notifications together in the watch notification
            center. For example, two scripts both using group "motion" will
            bundle into a single expandable stack instead of appearing as
            separate entries.
          default: ""
          selector:
            text:

mode: parallel
max: 10

sequence:
  - variables:
      bp_message: !input message
      bp_title: !input title
      bp_a1_title: !input action_1_title
      bp_a1: !input action_1
      bp_a2_title: !input action_2_title
      bp_a2: !input action_2
      bp_a3_title: !input action_3_title
      bp_a3: !input action_3
      bp_a4_title: !input action_4_title
      bp_a4: !input action_4
      bp_priority: !input priority
      bp_sound: !input sound
      bp_target_device: !input target
      bp_tag: !input tag
      bp_group: !input group
  - service: wrist_assistant.send_notification
    data: >
      {%- set d = namespace(items=[("message", bp_message), ("priority", bp_priority)]) -%}
      {%- if bp_title %}{%- set d.items = d.items + [("title", bp_title)] -%}{%- endif -%}
      {%- if bp_sound %}{%- set d.items = d.items + [("sound", bp_sound)] -%}{%- endif -%}
      {%- if bp_target_device -%}
        {%- set ids = device_attr(bp_target_device, 'identifiers') | list -%}
        {%- if ids %}{%- set d.items = d.items + [("target", ids[0][1] | replace('watch_', ''))] -%}{%- endif -%}
      {%- endif -%}
      {%- if bp_tag %}{%- set d.items = d.items + [("tag", bp_tag)] -%}{%- endif -%}
      {%- if bp_group %}{%- set d.items = d.items + [("group", bp_group)] -%}{%- endif -%}
      {%- set actions = namespace(list=[]) -%}
      {%- set slots = [
        (bp_a1_title, bp_a1),
        (bp_a2_title, bp_a2),
        (bp_a3_title, bp_a3),
        (bp_a4_title, bp_a4),
      ] -%}
      {%- for btn_label, steps in slots -%}
        {%- if steps is sequence and steps | length > 0 -%}
          {%- set step = steps[0] -%}
          {%- set full_svc = step.action | default(step.service | default('')) -%}
          {%- if full_svc -%}
            {%- set domain = full_svc.split('.')[0] -%}
            {%- set svc = full_svc.split('.')[1] | default(full_svc) -%}
            {%- set auto_title = svc | replace('_', ' ') | title -%}
            {%- set btn_title = btn_label if btn_label else auto_title -%}
            {%- set svc_data = step.data | default({}) -%}
            {%- set eid = '' -%}
            {%- if step.target is defined and step.target.entity_id is defined -%}
              {%- if step.target.entity_id is string -%}
                {%- set eid = step.target.entity_id -%}
              {%- elif step.target.entity_id is sequence and step.target.entity_id | length > 0 -%}
                {%- set eid = step.target.entity_id[0] -%}
              {%- endif -%}
            {%- endif -%}
            {%- set a = namespace(items=[("title", btn_title), ("domain", domain), ("service", svc)]) -%}
            {%- if eid %}{%- set a.items = a.items + [("entity_id", eid)] -%}{%- endif -%}
            {%- if svc_data %}{%- set a.items = a.items + [("service_data", svc_data)] -%}{%- endif -%}
            {%- set actions.list = actions.list + [dict(a.items)] -%}
          {%- endif -%}
        {%- endif -%}
      {%- endfor -%}
      {%- if actions.list %}{%- set d.items = d.items + [("actions", actions.list)] -%}{%- endif -%}
      {{ dict(d.items) }}
